version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-user1-dev-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-15347z4pdbtv4"
s3_prefix = "sam-app-user1-dev-stack"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"

[gdavidson]
[gdavidson.deploy]
[gdavidson.deploy.parameters]
stack_name = "sam-app-user1-dev-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-15347z4pdbtv4"
s3_prefix = "sam-app-user1-dev-stack"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
